name: NPM Artifactory Install
description: Installs npm dependencies from an artifactory repository.
inputs:

  default-shell:
    description: Default shell in which to run the action.
    required: false
    default: bash

  registry:
    description: Registry URL for artifactory repository.
    required: false
    default: https://profittools.jfrog.io/artifactory/api/npm/npm-local/

  token:
    description: Artifactory access token.
    required: true

runs:
  using: composite
  steps:
    - name: Set Artifactory User Email
      run: echo "email=irodriguez@profittools.net" >> .npmrc
      shell: ${{ inputs.default-shell }}

    - name: Force Auth
      run: echo "always-auth=true"
      shell: ${{ inputs.default-shell }}

    - name: Configure Artifactory Registry
      run: echo "registry=${{ inputs.registry }}" >> .npmrc
      shell: ${{ inputs.default-shell }}

    - name: Set Authorization Token
      run: echo "//profittools.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ inputs.token }}" >> .npmrc
      shell: ${{ inputs.default-shell }}

    - name: Publish Package
      run: npm publish --registry ${{ inputs.registry }}
      shell: ${{ inputs.default-shell }}
