name: Check Coverage
description: Check the coverage thresholds an uploads report to pull requests.
inputs:
  default-shell:
    description: Default shell in which to run the action.
    required: false
    default: bash
  thresholds:
    description: The minimum coverage thresholds to pass the action.
    required: false
    default: '75 85'
  report:
    description: The coverage report to generate.
    required: false
    default: output/coverage/unittests_coverage.xml
runs:
  using: composite
  steps:
    - name: Process Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ inputs.report }}
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: ${{ inputs.thresholds }}

    - name: List Coverage Report File
      if: always()
      run: |
        ls -l *.md
      shell: ${{ inputs.default-shell }}

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
