name: Setup Windows Environment
description: Sets environment for a Python application and its requirements-dev.txt

inputs:

  default-shell:
    description: Shell used to run steps.
    required: false
    default: pwsh

  index-url:
    description: URL for an index other than PyPI
    required: false
    default: PyPI

  requirements-file:
    description: File containing all the requirements to install.
    required: false
    default: requirements-dev.txt

  output-dir:
    description: Folder in which store all output files.
    required: false
    default: output

runs:
  using: composite
  steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Check Python Version
      run: python --version
      shell: ${{ inputs.default-shell }}

    - name: Install Requirements PyPI
      run: python -m pip install -r ${{ inputs.requirements-file }}
      if: ${{ inputs.index-url == 'PyPI' }}
      shell: ${{ inputs.default-shell }}

    - name: Install Requirements External
      run: python -m pip install -r ${{ inputs.requirements-file }} --index-url ${{ inputs.index-url }}
      if: ${{ inputs.index-url != 'PyPI' }}
      shell: ${{ inputs.default-shell }}

    - name: Display Installed Requirements
      run: pip list
      shell: ${{ inputs.default-shell }}

    - name: Create Output Directory
      run: mkdir ${{ inputs.output-dir }}
      shell: ${{ inputs.default-shell }}
      continue-on-error: true
      
    - name: Save Installed Requirements
      run: pip list > ${{ inputs.output-dir }}/installed-requirements.txt
      shell: ${{ inputs.default-shell }}