name: Install Requirements
description: Installs requirements based on the specified requirements file and index.
inputs:
  requirements-file:
    description: File containing the requirements to install.
    required: true
    default: requirements-dev.txt
  index-url:
    description: URL for an index other than PyPI
    required: false
runs:
  using: "composite"
  steps:
    - name: Update PIP
      run: python -m pip install --upgrade pip
      shell: defaults.run
    - name: Install Requirements 
      run: pip install -r ${{ inputs.requirements-file }}
      shell: defaults.run
    - name: Save Installed Requirements
      run: pip list > installed-requirements.txt
      shell: defaults.run
    - name: Display Installed Requirements
      run: pip list
      shell: defaults.run
      