name: Setup Environment
description: Installs Python and sets up the dependencies.
inputs:

  default-shell:
    description: Shell used to run steps.
    required: false
    default: bash

  python-version:
    description: Version of Python to use.
    required: false
    default: "3.9"

  requirements-file:
    description: File containing the requirements to install.
    required: false
    default: requirements-dev.txt

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Requirements
      uses: envasetechnologies/.github/actions/python/install-requirements@v1
      with:
        index-url: https://admin:${{ env.ART_PASSWORD }}@profittools.jfrog.io/profittools/api/pypi/pypi/simple
        default-shell: ${{ inputs.default-shell }}
        requirements-file: ${{ inputs.requirements-file }}
