name: Setup Environment
description: Installs Python and sets up the dependencies.
inputs:

  default-shell:
    description: Shell used to run steps.
    required: false
    default: bash

  python-version:
    description: Version of Python to use.
    required: false
    default: "3.9"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Requirements
      uses: envasetechnologies/.github/actions/python/install-requirements@v1
      with:
        index-url: https://admin:${{ secrets.artifactory-password }}@profittools.jfrog.io/profittools/api/pypi/pypi/simple
        default-shell: ${{ inputs.default-shell }}
