name: Setup UV
description: Setup Python Environment that Uses UV.
inputs:
  default-shell:
    description: Shell in which to execute the action.
    required: false
    default: bash

  python-version:
    description: Version of python to use.
    required: false
    default: '3.12'

runs:
  using: composite
  steps:

    - name: Install UV
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Dependencies
      run: uv sync
      shell: ${{ inputs.default-shell }}

    - name: Display Installed Requirements
      run: uv pip list
      shell: ${{ inputs.default-shell }}
