name: Deploy Chalice Application
description: Deploys a Chalice based Application
inputs:

  terraform-version:
    description: Version of Terraform to install.
    required: false
    default: "1.1.9"

  release-task:
    description: Bolt task that executes the commands to released.
    required: false
    default: "post-release"
  
  default-shell:
    description: Shell used to run steps.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      shell: ${{ inputs.default-shell }}
    
    - name: Deploy Chalice Application
      run: bolt ${{ inputs.release-task }}
      shell: ${{ inputs.default-shell }}
