name: Release
description: Releases a project.
inputs:
  default-shell:
    description: Default shell in which to run the action.
    required: false
    default: bash
  release-task:
    description: Bolt task that executes the commands to released.
    required: false
    default: "post-release"
runs:
  using: composite
  steps:  
    - name: Display Branch Name
      run: echo ${BRANCH_NAME}
      shell: ${{ inputs.default-shell }}
    # - name: Fetch Tags
    #   if: ${{ inputs.fetch-tags }}
    #   run: git fetch --tags
    #   shell: ${{ inputs.default-shell }}
    - name: Post Release
      run: bolt ${{ inputs.release-task }}
      shell: ${{ inputs.default-shell }}
