name: Setup Python
description: Setup Python Environment
inputs:

  default-shell:
    description: Shell in which to execute the action.
    required: false
    default: bash

  python-version:
    description: Version of python to use.
    required: false
    default: '3.11'

  requirements-file:
    description: File containing the requirements to install.
    required: true
    default: requirements-dev.txt

  index-url:
    description: Index from where to install packages
    required: false
    default: 'PyPI'

runs:
  using: composite
  steps:

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Requirements from PyPI
      if: ${{ inputs.index-url == 'PyPI' }}
      run: python -m pip install -r ${{ inputs.requirements-file }}
      shell: ${{ inputs.default-shell }}

    - name: Install requirementsequirements from ${{ inputs.index-url }}
      if: ${{ inputs.index-url != 'PyPI' }}
      run: python -m pip install -r ${{ inputs.requirements-file }} --index-url ${{ inputs.index-url }}
      shell: ${{ inputs.default-shell }}

    - name: Display Installed Requirements
      run: pip list
      shell: ${{ inputs.default-shell }}

