name: Bolt Unit Tests
description: Executes the unit tests generating result and coverage reports.
inputs:
  default-shell:
    description: Default shell in which to run the action.
    required: false
    default: bash
  task:
    description: Task that defines the execution of unit tests.
    required: false
    default: cov
  thresholds:
    description: The minimum coverage thresholds to pass the action.
    required: false
    default: '75 85'
  report:
    description: The coverage report to generate.
    required: false
    default: output/coverage/unittests_coverage.xml
runs:
  using: composite
  steps:
    - name: Execute Unit Tests
      env:
        pytest_verbosity: "1"
      uses: envasetechnologies/.github/actions/bolt@v3
      with:
        task: ${{ inputs.task }}

    - run: ls -R ./output
      shell: ${{ inputs.default-shell }}

    - name: Code Coverate Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ inputs.report }}
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: ${{ inputs.thresholds }}

    # - name: List Coverage Report File
    #   if: always()
    #   run: |
    #     ls -l *.md
    #   shell: ${{ inputs.default-shell }}

    # - name: Add Coverage PR Comment
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   if: github.event_name == 'pull_request'
    #   with:
    #     recreate: true
    #     path: code-coverage-results.md
