name: Build Python Envase Library

on: 
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-library-job:
    uses: envasetechnologies/.github/.github/workflows/python-library-build.yml@v1
    with:
      python-version: '["3.7", "3.8", "3.9"]'
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      msteams-webhook: ${{ secrets.PT_MSTEAMS_WEBHOOK}}