name: mkdocs-build
description: Builds MkDocs documentation project that uses `uv`
inputs:
  default-shell:
    description: Shell in which to execute the action.
    required: false
    default: bash

runs:
  using: composite
  steps:
    - name: Build documentation
      run: uv run mkdocs Build
      shell: ${{ inputs.default-shell }}
