name: Install Dependencies
description: Installs requirements based on the specified requirements file and index.
inputs:
  serverless-action:
    description: Serverless action you want to run, default is deploy.
    required: false
    default: deploy
  default-shell:
    description: Default shell in which to run the action.
    required: false
    default: bash
  node-versoin:
    required: false
    default: 16.x

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      shell: ${{ inputs.default-shell }}
      with:
        node-version: ${{ inputs.node-version }}
    - run: npm ci
    
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: ${{inputs.serverless-action}}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}