name: Render ECS Task Definition
description: takes in ecs task definition and updated the image
inputs:

  default-shell:
    description: Shell used to run steps.
    required: false
    default: bash

  task-def-path:
    description: relative path to your ecs task definition file.
    required: true

runs:
  using: composite
  steps:
    - name: Build task def from template
      shell: ${{inputs.default-shell}}
      run: chmod +x build_task_definition.sh && ./build_task_definition.sh

