name: Docker build and push to ECR
description: builds docker images, tags it with application version, and pushes to AWS ECR
inputs:

  default-shell:
    description: Shell used to run steps.
    required: false
    default: bash

  tag:
    description: Tag used when tagging docker image
    required: false

  ecr-uri:
    description: uri of the ECR repository you want your image pushed to e.g. 518892363268.dkr.ecr.us-east-1.amazonaws.com/envase-connect-build-agent
    required: true

  install-token:
    description: Token to access private packages during install
    required: false

runs:
  using: composite
  steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        shell: ${{inputs.default-shell}}
        run: >
          COMMAND_ARGS="-e ${{inputs.ecr-uri}}"

          if [ -v ${{inputs.install-token}} ]; then
            COMMAND_ARGS+=" -i ${{inputs.install-token}}"
            echo has install token - $COMMAND_ARGS
          fi

          if [ -v ${{inputs.tag}} ]; then
            COMMAND_ARGS+=" -t ${{inputs.tag}}"
            echo has image tag - $COMMAND_ARGS
          fi

          echo full args - $COMMAND_ARGS

          chmod +x build_push_docker.sh && ./build_push_docker.sh $COMMAND_ARGS
