name: Docker build and push to ECR
description: builds docker images, tags it with application version, and pushes to AWS ECR
inputs:

  default-shell:
    description: Shell used to run steps.
    required: false
    default: bash

  tag:
    description: Tag used when tagging docker image
    required: false

  ecr-uri:
    description: uri of the ECR repository you want your image pushed to e.g. 518892363268.dkr.ecr.us-east-1.amazonaws.com/envase-connect-build-agent
    required: true

  install-token:
    description: Token to access private packages during install
    required: false

runs:
  using: composite
  steps:
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        shell: ${{inputs.default-shell}}
        run: ./build_push_docker.sh ${{inputs.ecr-uri}} ${{inputs.install-token}} ${{ inputs.tag }}


